spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/regist-user
    username: postgres
    password: postgres
  mail:
    host: localhost
    port: 1025
server:
  servlet:
    context-path: /user