spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/regist-user
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: regist.user1005@gmail.com
    password: zlzwwsfkovbefuug
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
server:
  servlet:
    context-path: /user